# Generated by Django 5.2.1 on 2025-05-31 20:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(blank=True, help_text='Display Name', max_length=255)),
                ('role', models.CharField(blank=True, help_text='Role Name', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('profile_pic', models.ForeignKey(blank=True, help_text='About profile image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
