services:
  website:
    restart: unless-stopped
    build:
      context: website
      dockerfile: Dockerfile
    command: gunicorn website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./website/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17.5-alpine3.21
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

volumes:
  postgres_data:
