# Generated by Django 5.2.1 on 2025-05-30 23:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='affiliate_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='afilliate_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
