# Generated by Django 5.2.1 on 2025-05-30 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_brandsettings_affiliate_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandsettings',
            old_name='afilliate_text',
            new_name='affiliate_text',
        ),
    ]
