# Generated by Django 5.2.1 on 2025-06-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_formpage_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram URL', null=True),
        ),
    ]
