# Generated by Django 5.2.1 on 2025-05-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_brandsettings_logo_brandsettings_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsettings',
            name='brand_logo',
        ),
        migrations.AlterUniqueTogether(
            name='footertext',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='locale',
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
        migrations.DeleteModel(
            name='BrandSettings',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
