# Generated by Django 5.2.1 on 2025-06-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='teaser',
            field=models.CharField(blank=True, help_text='Short teaser text', max_length=255),
        ),
    ]
