# Generated by Django 5.2.1 on 2025-06-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publicationpage_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='purchase_link_drivethrough',
            field=models.URLField(blank=True, help_text='Offsite Purchase URL for Drivethrough RPG', null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='purchase_link_lulu',
            field=models.URLField(blank=True, help_text='Offsite Purchase URL for Lulu', null=True),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='purchase_link',
            field=models.URLField(blank=True, help_text='Offsite Purchase URL for Itch IO', null=True),
        ),
    ]
