# Generated by Django 5.2.1 on 2025-06-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publicationpage_purchase_link_drivethrough_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='purchase_link_drivethrough',
            field=models.URLField(blank=True, help_text='Offsite Purchase URL for DriveThru RPG', null=True),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='purchase_link_lulu',
            field=models.URLField(blank=True, help_text='Offsite Purchase URL for LULU', null=True),
        ),
    ]
